### ISSUE TITLE
Julia ImageView and GLMakie libraries unable to precompile in Docker

### ISSUE THREAD

**Issue by Treborsky** [aI-lab-glider/radiotherapy-plans-backend#11]
Przy budowaniu Dockerfile dla backendu w Julia napotkałem na problem ze zdjęcia.

![julia_docker_glmakie](https://user-images.githubusercontent.com/57878543/144824886-e92ad494-c2cd-4e93-9dd6-425684767310.png)

Krótko mówiąc, nie wykrywa ani OpenGL, ani żadnego Display'a, co ma sens, bo obraz Dockera nie ma dostępu do takich rzeczy.

Problem, co z tym zrobić? Czy konieczne jest użycie tych bibliotek?

**Comment by mateuszbaran** [comment]
Ani `ImageView` ani `GLMakie` nie są potrzebne na serwerze -- korzystam z nich tylko do interaktywnego testowania działania kodu. Można spokojnie funkcje korzystające z tych pakietów wydzielić do osobnego pliku.

**Comment by mateuszbaran** [comment]
Zajmę się tym jak będę miał chwilę i przy okazji przeniosę usprawnienia które zrobiłem na potrzeby analizy nowych planów.

**Comment by Treborsky** [comment]
Ok, usunąłem je ręcznie na próbę i udało mi się zrobić Dockerfile, który może posłużyć do odpalenia Julii, także myślę, że sprawa załatwiona. Zostaje docker compose, gdzie wystawiamy odpowiednie porty i backend jest w miare gotowy
