### ISSUE TITLE
Używanie Julii w procesie Pythona

### ISSUE THREAD

**Issue by Treborsky** [aI-lab-glider/radiotherapy-plans-backend#2]
Udało się wykorzystać do tego celu bibliotekę [`julia`](https://pypi.org/project/julia/). Działa to tak, że możemy wykorzystać paczki Julia i funkcje z tych paczek w Pythonie jako normalnie funkcje. Wygląda to jakoś tak:  
```
# skrypt pythona
import julia                 # importujemy moduł
julia.install()              # "instalujemy" julia 
from julia import Base       # możemy używać paczek z Julii

print(f'result: ', Base.sind(90))
```
W konsoli:  
`result: 1.0`  
 Trzeba więc zrobić paczkę i udostępnić odpowiednie API dla skryptu Pythona. Wtedy można bez problemu odpalać tworzenie meshy.

**Comment by mateuszbaran** [comment]
Aktywacja środowiska Julii w PyJulia:
https://stackoverflow.com/a/64600278

**Comment by Treborsky** [comment]
Udało się utworzyć moduł (trzeba było usunąć linijki, w których odpalamy faktycznie obliczenia -> i tak zrobimy to w Pythonie). Pozostaje więc kwestia jakiegoś utrzymania tej paczki. Z dokumentacji wynika, że jesteśmy w stanie pisać dla tej paczki testy oraz dodać ją do różnych repozytoriów. Warto by było to przedyskutować.  
![image](https://user-images.githubusercontent.com/57878543/131386825-b865e454-ee0e-4160-9a42-df45d4812166.png)

**Comment by Qwebeck** [comment]
Czy to nie jest tak, że utrzymanie jest potrzebne tylko wtedy kiedy publikujemy tę paczkę w sieci na jakimś odpowiedniku PyPi dla Julii? 
Natomiast jeśli to jest tylko dla wewnętrznego użytku to chyba nie musimy się o to martwić?

**Comment by Treborsky** [comment]
No raczej nie musimy, tak tylko pytam czy od razu chcemy wszystko tam władować. Może nie warto, bo to za dużo pracy

**Comment by mateuszbaran** [comment]
Póki co to nie planowałem rejestracji tego kodu w Julii jako pakietu (Julia ma od tego General registry: https://github.com/JuliaRegistries/General/ ), natomiast testy powinno się dać tak czy siak zrobić w jednym repozytorium z Pythonem.
