### ISSUE TITLE
Julia API method implementations

### ISSUE THREAD

**Issue by Treborsky** [aI-lab-glider/radiotherapy-plans-backend#6]
In order to make the API work, I need some insight into how the script works. To be concrete, what interests me is:
 1. how to initialize the structure on which the calculations will be performed
 2. how to call all available methods (I know only two will be called for certain - the ROI mesh one and CT one)

This is the API method for CT mesh, the one below is for ROI
https://github.com/Project-Summer-AI-Lab-Glider/radiotherapy-plans-backend/blob/117e8fe0468771604646c6324393b1694b6bda93/computation/src/RadiotherapyPlansBackend.jl#L382

**Comment by mateuszbaran** [comment]
I think apart from `ct_mesh_from_files` and `make_ROI_mesh`, only `load_DICOMs` needs to be directly called as a result of a web request. Here is an example of its usage: https://github.com/Project-Summer-AI-Lab-Glider/radiotherapy-plans-backend/blob/main/src/RadiotherapyPlansBackend.jl#L333-L337 . This should answer both questions I think?

Could you add an API for start and end of a session? Does `MakeCtMesh` receive the isodose level for making the mesh (it's just a floating point number)? What are the paths to received and unpacked DICOM paths? Does `MakeRoiMesh` receive the ROI name (a string)?

**Comment by Treborsky** [comment]
First, to answer your questions.
1. Yes, I probably could, but right now I do not have a great idea of what a session would be in this case
2. It does / it will (when the api in julia is done)
3. The dicoms will be already unzipped and separated into three folders. The folder names will be exactly the same as those given in the frontend, before zipping

I suppose, I will begin by downloading some proper dicom file set and loading it via the api.
